### ISSUE TITLE
Some SoPNs seem to be out by a day

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/uk-election-timetables#15]
I've been a bit confused by the dates displaying on WCIVF and have had a look at this, I'm not sure how it's all calculated but I think our dates for PCC & Senedd are out by a day. Should be 9 Apr, eg: https://www.valeofglamorgan.gov.uk/en/our_council/Council-Structure/Elections/Senedd-Cymru-Elections-RRO.aspx; https://www.valeofglamorgan.gov.uk/en/our_council/Council-Structure/Police-and-Crime-Commissioner-Elections-2020/South-Wales-Police-and-Crime-Commissioner-Elections-PARO.aspx

There might also be issues with the Scot parl. (it might be 31 Mar?)

**Comment by symroe** [comment]
My understanding is that the confusion here is between "first date a SoPN can be published" and "last date a SoPN can be published".

Is that right, @pmk01?

I think we should add both, as both are useful to us in different ways.
