### ISSUE TITLE
Add voter ID card registration date

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/uk-election-timetables#18]
There is a chance that before May 2023 Voter ID cards will be introduced for some UK elections.

Voter ID will be in the form of existing IDs that might be held by would be voters, but there is provision for voters to apply for a special voter ID document.

The provisional deadline to apply for this document will be  working days before the poll.

There is no work to be done on this just yet, as the plans aren't implemented. We will need to add this deadline to the library if / when it does happen.

**Comment by symroe** [comment]
Relates to https://github.com/DemocracyClub/EveryElection/issues/1729. Not all elections will require voter ID. This library shouldn't worry about that in the case of local elections, but shouldn't return voter ID deadlines for elections that never require voter ID

**Comment by symroe** [comment]
@pmk01 do we know the timetable for this yet? Something tells me it's 10 working days?

**Comment by pmk01** [comment]
Ahead of a specific election, referendum, or recall petition, the deadline for application will be 5pm, 6 working days before either the date of the poll or the last day for signing the petition.

If you apply for a Voter Authority Certificate after this date, you will not be able to use your Voter Authority Certificate at that poll or recall petition.

Source: https://www.electoralcommission.org.uk/media/5535

**Comment by symroe** [comment]
Splendid, thanks!
