### ISSUE TITLE
City of London

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/uk-election-timetables#8]
City of London Corporation Common Council election SoPNs are published ~17 days~ 16 days before the election. See p.74 of this handy PDF: https://www.cityoflondon.gov.uk/assets/About-us/wardmote-book-june-2014.pdf

(all the other dates are different too, I expect)

**Comment by mrwilson** [comment]
Thanks @pmk01 - I took a look at the timetables, they seem to _not_ include Saturday in the calculation and _do_ include a new-to-the-library concept of a "Christmas break" and "Easter break", supposedly set out in an Act of Common Council passed in 1970

> Excludes Sundays, the Christmas Break, the Easter Break, bank holidays and days appointed for public thanksgiving or mourning (Section 1 of the Act of Common Council of 9 April 1970 – see Part A, Section 4 “Notice of Election to Notice of Poll”, paragraph 6 at page 19).

However, I can't actually find this Act anywhere (yet). Please let me know if you have better luck sniffing it out!

**Comment by GeoWill** [comment]
Bit more info from the CoL via an email exchange with @pmk01:

>There isn’t an electoral cycle for Aldermanic elections I’m afraid. Aldermen stand down once they have served their 6 year term or turned 70 years old. This means they are essentially on a rolling basis that tends to be staggered throughout the years.  It’s never the case that all 25 will be up for election at once.
Aldermen have not yet agreed to when they would like to hold the upcoming Aldermanic elections, so we don’t know how many, if any, will be held in March. There are 9 Aldermanic elections that are due to go ahead this year.

I don't think the library should try and capture this - but maybe it should be noted somewhere in case anyone tries to do something about it in the future. This is seperate to any cycle that may or may not exists for the councillors...

**Comment by pmk01** [comment]
To follow up @mrwilson's original question, I don't think the 1970 Act appears online anywhere. Next time I'm in London I'll, er, pop in and ask to see a copy...

**Comment by chris48s** [comment]
TODO: host this somewhere sensible

[19700409 Act of Common Council of 9 April 1970.docx](https://github.com/user-attachments/files/17617342/19700409.Act.of.Common.Council.of.9.April.1970.docx)

**Comment by pmk01** [comment]
> City of London Corporation Common Council election SoPNs are published 17 days before the election. See p.74 of this handy PDF: https://www.cityoflondon.gov.uk/assets/About-us/wardmote-book-june-2014.pdf
> 
> (all the other dates are different too, I expect)

Returning to this, SoPNs are published 17 days before but withdrawals are possible 16 days before, meaning that it's common for the SoPNs to be updated / republished. This happened last time, to our confusion. So we should date it 16 before.

[Page 25.](https://www.cityoflondon.gov.uk/assets/about-us/voting-elections/wardmote-book-september-2022.pdf)
